### ISSUE TITLE
How to initialize test environment packages?

### ISSUE THREAD

**Issue by findmyway** [JuliaTesting/ReTestItems.jl#143]
Let's say I have a test file which contains the following code:

```julia
@testitem "A" begin
    using Random
    rng = Random.MersenneTwister(123)
end
```

When executing `runtests`, it will complain that 

```
Error During Test at /tmp/Foo/src/foo_test.jl:1
  Got exception outside of a @test
  ArgumentError: Package Random not found in current path.
  - Run `import Pkg; Pkg.add("Random")` to install the Random package.
```

I tried to add the `worker_init_expr`:

```julia
worker_init_expr = quote
    using Pkg; Pkg.add("Random")
end

runtests(Foo; worker_init_expr)
```

Then I get:

```
ERROR: LoadError: TaskFailedException

    nested task error: ArgumentError: Package Pkg not found in current path.
    - Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.
    Stacktrace:
```

More generally, how could we initialize the worker so that it will find pkgs under the `[targets]` section in `Project.toml` file?

**Comment by nickrobinson251** [comment]
`runtests` should already activate the test environment (i.e. including loading the package under `[targets]`). you should not need to load them in the `worker_init_expr`

Can you share the repo where you're seeing this, so i can see what could be going wrong?

Also, could you try running with `debug=2` and seeing which of these log messages appear:
https://github.com/JuliaTesting/ReTestItems.jl/blob/60d93f19081012533326b0a0d55367e46dee78aa/src/ReTestItems.jl#L291-L310

**Comment by findmyway** [comment]
Thanks for looking into it!

While trying to reproduce the error above, I noticed that the most likely reason is that I only added the dependency (`Random`) under the `[extras]` section and forgot to add it into the `tests` target.

Really appreciate your time.

**Comment by nickrobinson251** [comment]
no worries -- relieved to here it was easily resolved 😅
