### ISSUE TITLE
Statically parse, rather than run, test files to extract `@testitem`s

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaTesting/ReTestItems.jl#41]
We could change the `@testitem` scanning from calling `include` to instead parsing the files (e.g. `Meta.parse(read(file, String))`) then walk the AST looking for top-level `@testitem`s that we then `eval`. 

This would have a few potential benefits:
- We could error on any non-top-level `@testitem`s (/ `@testsetup`s)
- We could `@warn` on `@testitem`s that were not in `_test.jl` files
- We could error on any top-level code in `_test.jl` files that's not a `@testitem` (or `@testsetup`)
- We wouldn’t necessarily _need_ the `_test.jl` suffix, since we could scan any file and just `eval` the `@testitem`

This is also more similar to what the VS Code extension does (#18)

**Comment by NHDaly** [comment]
> We wouldn’t necessarily need the `_test.jl` suffix, since we could scan any file and just `eval` the `@testitem`

One possible policy that i think could be good for everyone would be any file that contains a `@testitem` or `@testsetup` must _only_ contain testitems and testsetups. That could be a way to do away with the `_test.jl` suffix and still keep the other benefits of catching malformed testitems.

(But this aspect is much less relevant than the main thrust of what you're describing here, and i'd rather start with what you proposed 👍)

**Comment by NHDaly** [comment]
@nickrobinson251 oh haha sorry i forgot we'd already detailed these steps. sorry i spammed it on that slack thread!

**Comment by nickrobinson251** [comment]
i'm still gonna add you suggestion here 😁 

> literally replace include() with this simple function that does exactly the same thing:
>
> ```julia
>   julia> function my_include(file)
>           block = Meta.parse("begin\n" * read(file, String) * "\nend")
>           exprs = block.args
>           for expr in exprs
>               eval(expr)
>           end
>       end
> ```
>
> We can just start with that, which is a noop change, and then literally just add some super tiny error checks in there that each expression is either at `@testitem` or a `@testsetup` and boom we've done it, and now we've switched to the "static parsing" approach but everything else is unchanged! :)
>
> We can even continue to run includes as well, if we want to, to make the transition easier

**Comment by NHDaly** [comment]
we didn't end up doing this yet, did we? Just trying to remember and clean up issues

**Comment by nickrobinson251** [comment]
In https://github.com/JuliaTesting/ReTestItems.jl/pull/78 we switched to first iterating over the parsed `Expr`s as part of the `include`, so we can assert that every `Expr` is a `@testitem` or `@testsetup` macro call. But we still only `include` files with the `_test.jl` or `_testsetup.jl` suffix.

**Comment by nickrobinson251** [comment]
After #170 (+ #179) we just parse the file to do all selection/filtering of `@testitem`s (by `name` or `tags`)

I'm closing this issue as done and have opened an issue for the remaining idea from this thread: https://github.com/JuliaTesting/ReTestItems.jl/issues/181
